Add DC RMS Voltage Measurement
NI-MeasurementLink-Plug-Ins/pcba-fct pull request #14
Opened 2024-03-19 04:17 UTC by kena0405

### What does this Pull Request accomplish?

- This measurement includes a LabVIEW project and measurement service library that automatically generated by 'Measurement Plug-in'.
- The VIs in the library are updated to support NI-DMM DC RMS Volatge measurements.
- A TestStand sequence file is included to show how to configure the pin map, register instrument sessions with the session management service, and run a measurement.
- InstrumentStudio files are included to show the manual testing.
- A Pin map file is included.
- A readme file is included.

### Why should this Pull Request be merged?

Adding this as one of the PCBA Function Test meausrements.

### What testing has been done?
Test setup:
- NI PXIe-6361 (DUTsimulator) AO1 is connected to NI PXIe-4081 (DMM1) CH0.
- The output signal of PXIe-6361: Voltage DC, 2 volts amplitude.

- In InstrumentStudio:
 ![image](https://github.com/NI-MeasurementLink-Plug-Ins/pcba-fct/assets/110214299/d112d473-34d0-4214-b655-8e26989a88a7)
- In TestStand:
![image](https://github.com/NI-MeasurementLink-Plug-Ins/pcba-fct/assets/110214299/01aec650-2bdf-4c19-ae79-57a01d4b16b9)

2024-03-19 18:15 UTC, kirstyong requested changes
@kena0405 Looks great overall! I tested it with a sinewave input and that looked good as well. I'd like to get @nathan-murphy's input on whether we want to merge this measurement with the Current measurement and confirm the measurement builds successfully before approving. If you could also add a link to this PR in the AzDo user stories of the measurement that would be great for tracking.

2024-03-19 18:15 UTC, kirstyong commented on src/NI-DMM DC RMS Voltage/NIDmmDCRmsVoltage/Get Type Specializations.vi
Can you fill in the constant for this VI? Should only need to do it for 1 element which is pin input.

2024-03-19 18:15 UTC, kirstyong commented on src/NI-DMM DC RMS Voltage/NIDmmDCRmsVoltage/Measurement UI.vi
@nathan-murphy were there any specific default values you wanted displayed for the user? This is what Carol has currently.
![image](https://github.com/NI-MeasurementLink-Plug-Ins/pcba-fct/assets/134538964/e8832fc3-c83d-46f8-a399-2856452fb83d)

2024-03-19 18:15 UTC, kirstyong commented on src/NI-DMM DC RMS Voltage/README.md
> +- InstrumentStudio 2024Q1 or later
Sorry to be picky, can you add a space between the year of the version and the quarter it was released? e.g. 2024 Q1

2024-03-19 21:10 UTC, kirstyong commented on src/NI-DMM DC RMS Voltage/NIDmmDCRmsVoltage/Measurement Logic.vi
Could you also add a `niDMM reset.vi` after you take the DC RMS measurement and before you close the session?
![image](https://github.com/NI-MeasurementLink-Plug-Ins/pcba-fct/assets/134538964/dace4f1e-1f06-4d35-b36e-66056d41a3f8)

We learned about this from working on the demo and running into some scenarios in TS where the instrument may be left in some "weird" state before the session is closed if you don't explicitly add a `reset` to set the instrument back to a "known" state. This is mostly to minimize errors in TS if you run the measurement multiple times in a row. It may or may not be more or less necessary depending on the driver, but as a better practice, I recommend we do it for all measurements.

2024-03-20 07:30 UTC, kena0405 commented on src/NI-DMM DC RMS Voltage/NIDmmDCRmsVoltage/Typedefs/Function.ctl
This is what I was thinking and investigated yesterday. The logic is almost the same except the Function type. 
For the Configuration as for PXIe-4081, the Range is different as DC Current measurement, which is 1uA, 10uA,100uA, 1mA, 10mA, 100mA,1A, 3A, different from the Voltage range 100mV, 1V, 10V, 100V, 1000V, so if we enter with the correct Range for both Voltage and Current, they can be merged together. Other differences are probably texture and units that we can adjust to be fit for both of them.

2024-03-20 07:39 UTC, kena0405 commented on src/NI-DMM DC RMS Voltage/NIDmmDCRmsVoltage/Measurement UI.vi
For PXIe-4081, it has a Onboard1.8 MS/s Isolated Digitizer per the specification. The default Sample Rate in the LabVIEW example is 1.8M with 1k waveform points. I picked the number to show 2 periods of sine signal, but of course we can change it from @nathan-murphy input. 
![image](https://github.com/NI-MeasurementLink-Plug-Ins/pcba-fct/assets/110214299/c672d04f-d522-430d-9465-cd17617396db)

2024-03-20 09:31 UTC, kena0405 commented on src/NI-DMM DC RMS Voltage/NIDmmDCRmsVoltage/Get Type Specializations.vi
done

2024-03-20 09:32 UTC, kena0405 commented on src/NI-DMM DC RMS Voltage/NIDmmDCRmsVoltage.lvproj
Yes, it was built successfully. Do I need to commit the exe in here? I see there is time for package tasks in our backlog so not sure if this is the tasks we need do right now.

2024-03-20 09:35 UTC, kena0405 commented on src/NI-DMM DC RMS Voltage/NIDmmDCRmsVoltage/Measurement Logic.vi
done

2024-03-20 12:27 UTC, kirstyong commented on src/NI-DMM DC RMS Voltage/NIDmmDCRmsVoltage.lvproj
No need to commit exe in here. I just want to make sure we aren't submitting any measurements that don't build.

2024-03-20 12:42 UTC, nathan-murphy commented on src/NI-DMM DC RMS Voltage/NIDmmDCRmsVoltage/Typedefs/Function.ctl
You could hide the label and show the caption for controls with units. Then when the user selects voltage or current, you can dynamically change the caption text for the specific controls. That's my recommendation. Here's an example:
[Changing Caption Demo.zip](https://github.com/NI-MeasurementLink-Plug-Ins/pcba-fct/files/14666630/Changing.Caption.Demo.zip)

2024-03-20 12:45 UTC, nathan-murphy commented on src/NI-DMM DC RMS Voltage/NIDmmDCRmsVoltage/Measurement UI.vi
As-is this will measure for 2 seconds, which could be 2 period of the signal was 1 Hz. I don't think that we can assume a specific frequency. Generally, we want to create responsive User Interfaces, so having 2 seconds after pressing 'Run' where the UI doesn't update may make users think that the code is slow. I think the defaults that are provided in the LV example are good ones to use as defaults.

2024-03-20 12:55 UTC, nathan-murphy commented on src/NI-DMM DC RMS Voltage/NIDmmDCRmsVoltage/Measurement UI.vi
Please ensure consistent spacing between controls in the Configuration section.

2024-03-20 22:43 UTC, kirstyong approved these changes

2024-03-20 22:51 UTC, kirstyong commented on src/NI-DMM DC RMS Voltage/NIDmmDCRmsVoltage/Typedefs/Function.ctl
Whoa that's neat @nathan-murphy. @kena0405 let's go ahead and submit this PR treated as just a voltage measurement. Instead of making individual current measurement next, you can go ahead and either rename this project or make a new one called `NI-DMM DC RMS Measurement` and include both Voltage and Current measurements functionality. Feel free to ping me offline with any questions. 😊

2024-03-20 22:53 UTC, kirstyong approved these changes

2024-03-20 22:53 UTC, kirstyong commented on src/NI-DMM DC RMS Voltage/README.md
> +This example performs DC volatge RMS measurement using NI DMM.
"voltage" typo

2024-03-21 06:52 UTC, kena0405 commented on src/NI-DMM DC RMS Voltage/NIDmmDCRmsVoltage/Measurement UI.vi
![Uploading image.png…]()

2024-03-21 07:47 UTC, merged