Scope Frequency Domain Measurement
NI-MeasurementLink-Plug-Ins/pcba-fct pull request #22
Opened 2024-04-09 06:04 UTC by Jay-Cao123

### What does this Pull Request accomplish?

- This measurement includes a LabVIEW project and measurement service library that automatically generated by 'Measurement Plug-in'.
- The VIs in the library are updated to support NI-SCOPE Frequency Domain measurements.
- A TestStand sequence file is included to show how to configure the pin map, register instrument sessions with the session management service, and run a measurement.
- InstrumentStudio files are included to show the manual testing.
- A Pin map file is included.
- A readme file is included.

### Why should this Pull Request be merged?

Adding this as one of the PCBA Function Test measurements.

### What testing has been done?

Test setup:

NI PXIe-5122 (SCOPE1) CH1 is connected to NI PXIe-4071 (DAQmx1) AO1.
The output signal of AO1: Voltage sinewave, 2 volts amplitude, 1Hz.
![image](https://github.com/NI-MeasurementLink-Plug-Ins/pcba-fct/assets/83160510/97935152-7627-44a0-b27c-b14a0da93479)

Test result:
InstrumentStudio:
![image](https://github.com/NI-MeasurementLink-Plug-Ins/pcba-fct/assets/83160510/e57f45e8-babd-4e7e-a85b-a53223a9f095)
TestStand:
![image](https://github.com/NI-MeasurementLink-Plug-Ins/pcba-fct/assets/83160510/83b80086-431c-4567-af48-228ea63734c7)

Build result:
![image](https://github.com/NI-MeasurementLink-Plug-Ins/pcba-fct/assets/83160510/cedf4aab-a852-4bdd-b8c5-6fe6ad00f3be)

2024-04-09 13:47 UTC, nathan-murphy requested changes

2024-04-09 21:23 UTC, kirstyong requested changes
Overall looks good! I validated it with a different frequency sinewave (10Hz) from a DAQmx example and can see that is returned with the right amplitude. 👍  Please add a readme and are the screenshots in the PR from testing using the built exe? If so, could you include that in a note in the PR description. Thanks!

![image](https://github.com/NI-MeasurementLink-Plug-Ins/pcba-fct/assets/134538964/c4b15dfb-f934-4605-9f08-9e2eab45b045)

2024-04-09 21:23 UTC, kirstyong commented on src/NIScopeFrequencyDomain/NIScopeFrequencyDomain/SubVI/Magnitudes Measurement.vi
Could you do a quick run through of your logic VI and subVI's and just make sure that wires entering/exiting vi's are aligned with where they are meant to enter/exit visually? ex. below to move bottom wire going into Magnitude RMS to be moved to left a bit

![image](https://github.com/NI-MeasurementLink-Plug-Ins/pcba-fct/assets/134538964/13e5e864-cc5e-463d-8324-f138e30ab43f)

2024-04-10 09:52 UTC, Jay-Cao123 commented on src/NIScopeFrequencyDomain/NIScopeFrequencyDomain/Measurement UI.vi
So in order to set the x-axis starting as 1Hz, I dis-select the "auto-scale" and make it as :
![image](https://github.com/NI-MeasurementLink-Plug-Ins/pcba-fct/assets/83160510/042a8811-ce0e-45de-8559-e0c83dd13ad0)

For a 1kHz sinewave, here's the graph:
![image](https://github.com/NI-MeasurementLink-Plug-Ins/pcba-fct/assets/83160510/565fb41c-80cc-4bac-a1e0-0cdfeb53506d)
For a 1Hz sinewave, here's the graph:
![image](https://github.com/NI-MeasurementLink-Plug-Ins/pcba-fct/assets/83160510/0b532698-a6d2-49ce-9459-b3e63a25fc77)
Is this what you want?

2024-04-10 18:17 UTC, nathan-murphy commented on src/NIScopeFrequencyDomain/NIScopeFrequencyDomain/Measurement UI.vi
Here's how you can convert numeric types into SI notation pretty easily:

![image](https://github.com/NI-MeasurementLink-Plug-Ins/pcba-fct/assets/10726539/17601cfc-12ce-441e-8959-8cf59bb58997)

2024-04-10 18:19 UTC, nathan-murphy commented on src/NIScopeFrequencyDomain/NIScopeFrequencyDomain/Measurement UI.vi
Thanks for providing screenshots. They look strange with the forced range on the x-axis. I think we can turn autoscaling back on, but definitely leave it in log scale.

2024-04-10 18:27 UTC, nathan-murphy approved these changes

2024-04-11 07:32 UTC, kena0405 approved these changes

2024-04-11 07:56 UTC, Jay-Cao123 commented
Final UI:
![image](https://github.com/NI-MeasurementLink-Plug-Ins/pcba-fct/assets/83160510/4cca3e1f-05e6-4849-bb3c-1eeb163c2975)

2024-04-11 15:14 UTC, kirstyong approved these changes

2024-04-11 15:14 UTC, kirstyong commented on src/NIScopeFrequencyDomain/README.md
> +- InstrumentStudio 2024Q1 or later
Small change, can you add a space between 2024 and Q1 for all of these? Thanks!

2024-04-12 02:41 UTC, merged